language: node_js

#safelist
branches:
  only:
  - master
  - stable

cache:
  directories:
  - "client/node_modules"
  - "api/node_modules"
  
before_install:
  - npm i -g npm@6.6.0
  
script:
  # npm install api and client
  - cd api
  - npm ci
  - cd ..
  - cd client
  - npm ci
  - cd ..
  
  # Now use serverless to deploy api
  - cd api
  - npm run deploy
  - cd ..
  
  # Now build and deploy client
  - cd client
  - npm run build
  - npm run deploy
